name: Nx Monorepo CI + GitHub Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-

      - name: Install dependencies
        run: npm install

      - name: Cache Nx output 
        uses: actions/cache@v4
        with:
          path: |
            .nx/cache
          key: nx-cache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            nx-cache-${{ github.ref }}-
            nx-cache-

      - name: Install latest Nx globally
        run: npm install -g nx@latest

      - name: Format Check
        run: npm run format

      - name: Lint All
        run: npm run lint

      - name: Build All Apps
        run: npm run build

      - name: Test All
        run: npm run test

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-

      - name: Install dependencies
        run: npm install

      - name: Install latest Nx globally
        run: npm install -g nx@latest

      - name: Cache Nx output
        uses: actions/cache@v4
        with:
          path: |
            .nx/cache
          key: nx-cache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            nx-cache-${{ github.ref }}-
            nx-cache-
            
      - name: Deploy All Apps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy